# Generated by Django 2.2.7 on 2019-11-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='delete_time',
        ),
        migrations.AddField(
            model_name='note',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
