# Generated by Django 2.2.7 on 2019-11-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191111_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='trash',
        ),
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
