# Generated by Django 2.2.7 on 2019-11-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20191112_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='delete_time',
            new_name='trash_delete_time',
        ),
    ]
