# Generated by Django 2.2.7 on 2019-11-30 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_auto_20191128_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='users',
        ),
        migrations.AddField(
            model_name='note',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborating_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
