# Generated by Django 2.2.7 on 2019-12-03 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0009_auto_20191202_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveField(
            model_name='note',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='note',
            name='color',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_pin',
        ),
        migrations.RemoveField(
            model_name='note',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='note',
            name='order',
        ),
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='note',
            name='trash_delete_time',
        ),
        migrations.CreateModel(
            name='NoteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archive', models.BooleanField(default=False)),
                ('is_pin', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(choices=[('W', 'White'), ('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('P', 'Pink'), ('V', 'Violet')], default='W', max_length=1)),
                ('is_owner', models.BooleanField(default=False)),
                ('trash_delete_time', models.DateTimeField(blank=True, null=True)),
                ('labels', models.ManyToManyField(blank=True, to='notes.Label')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='note',
            name='users',
            field=models.ManyToManyField(through='notes.NoteConfig', to=settings.AUTH_USER_MODEL),
        ),
    ]
