# Generated by Django 2.2.7 on 2019-12-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20191203_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
    ]
