# Generated by Django 2.2.7 on 2019-12-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_remove_label_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCheckListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('H', 'Hidden'), ('T', 'Done'), ('F', 'Not Done')], default='H', max_length=1)),
                ('text', models.CharField(max_length=950)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.DeleteModel(
            name='NoteContent',
        ),
    ]
