# Generated by Django 2.2.7 on 2019-12-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20191203_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteCheckListItem',
            new_name='Item',
        ),
    ]
