# Generated by Django 2.2.7 on 2019-12-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20191203_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='NoteContent',
        ),
    ]
