# Generated by Django 2.2.7 on 2019-12-05 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0015_auto_20191203_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteConfig',
            new_name='NoteSetting',
        ),
    ]
