# Generated by Django 2.2.7 on 2019-12-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20191205_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesetting',
            old_name='is_pin',
            new_name='is_pinned',
        ),
    ]
