# Generated by Django 2.2.7 on 2019-12-07 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0018_auto_20191207_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(choices=[('W', 'White'), ('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('P', 'Pink'), ('V', 'Violet')], default='W', max_length=1)),
                ('is_owner', models.BooleanField(default=False)),
                ('trash_delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SettingLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Label')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Setting')),
            ],
        ),
        migrations.RenameModel(
            old_name='NoteContent',
            new_name='Content',
        ),
        migrations.AlterField(
            model_name='note',
            name='users',
            field=models.ManyToManyField(through='notes.Setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NoteSetting',
        ),
        migrations.AddField(
            model_name='setting',
            name='labels',
            field=models.ManyToManyField(blank=True, through='notes.SettingLabel', to='notes.Label'),
        ),
        migrations.AddField(
            model_name='setting',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
        migrations.AddField(
            model_name='setting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('user', 'note')},
        ),
    ]
