# Generated by Django 2.2.7 on 2019-12-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_auto_20191207_0956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settinglabel',
            unique_together={('label', 'setting')},
        ),
    ]
